<?php

return array(
    array('being', array('existance', '存在', 'そんざい'), array (
        'b' => 
        array (
            'existance' => 0,
            '存在' => 0,
            'そんざい' => 0,
        ),
        'be' => 
        array (
            'existance' => 0,
            '存在' => 0,
            'そんざい' => 0,
        ),
        'bei' => 
        array (
            'existance' => 0,
            '存在' => 0,
            'そんざい' => 0,
        ),
        'bein' => 
        array (
            'existance' => 0,
            '存在' => 0,
            'そんざい' => 0,
        ),
        'being' => 
        array (
            'existance' => 0,
            '存在' => 0,
            'そんざい' => 0,
        ),
    )),
);