<?php

return array(
    array('being', 'existence', array (
        'b' => 
        array (
            'existence' => 0,
        ),
        'be' => 
        array (
            'existence' => 0,
        ),
        'bei' => 
        array (
            'existence' => 0,
        ),
        'bein' => 
        array (
            'existence' => 0,
        ),
        'being' => 
        array (
            'existence' => 0,
        ),
    )),
    array('being', '存在', array (
        'b' => 
        array (
            '存在' => 0,
        ),
        'be' => 
        array (
            '存在' => 0,
        ),
        'bei' => 
        array (
            '存在' => 0,
        ),
        'bein' => 
        array (
            '存在' => 0,
        ),
        'being' => 
        array (
            '存在' => 0,
        ),
    )),
    array('being', 'そんざい', array (
        'b' => 
        array (
            'そんざい' => 0,
        ),
        'be' => 
        array (
            'そんざい' => 0,
        ),
        'bei' => 
        array (
            'そんざい' => 0,
        ),
        'bein' => 
        array (
            'そんざい' => 0,
        ),
        'being' => 
        array (
            'そんざい' => 0,
        ),
    )),
);