<?php

return array(
    array('existence', array (
        'e' => 
        array (
            'existence' => 0,
        ),
        'ex' => 
        array (
            'existence' => 0,
        ),
        'exi' => 
        array (
            'existence' => 0,
        ),
        'exis' => 
        array (
            'existence' => 0,
        ),
        'exist' => 
        array (
            'existence' => 0,
        ),
        'existe' => 
        array (
            'existence' => 0,
        ),
        'existen' => 
        array (
            'existence' => 0,
        ),
        'existenc' => 
        array (
            'existence' => 0,
        ),
        'existence' => 
        array (
            'existence' => 0,
        ),
    )),
    array('存在', array (
        '存' => 
        array (
            '存在' => 0,
        ),
        '存在' => 
        array (
            '存在' => 0,
        ),
    )),
    array('そんざい', array (
        'そ' => 
        array (
            'そんざい' => 0,
        ),
        'そん' => 
        array (
            'そんざい' => 0,
        ),
        'そんざ' => 
        array (
            'そんざい' => 0,
        ),
        'そんざい' => 
        array (
            'そんざい' => 0,
        ),
    )),
);
