<?php

return array(
    array(array('existance', '存在', 'そんざい'), array (
        'existance' => array(
            'e' => 
            array (
                'existance' => 0,
            ),
            'ex' => 
            array (
                'existance' => 0,
            ),
            'exi' => 
            array (
                'existance' => 0,
            ),
            'exis' => 
            array (
                'existance' => 0,
            ),
            'exist' => 
            array (
                'existance' => 0,
            ),
            'exista' => 
            array (
                'existance' => 0,
            ),
            'existan' => 
            array (
                'existance' => 0,
            ),
            'existanc' => 
            array (
                'existance' => 0,
            ),
            'existance' => 
            array (
                'existance' => 0,
            ),
        ),
        '存在' => array (
            '存' => 
            array (
                '存在' => 0,
            ),
            '存在' => 
            array (
                '存在' => 0,
            ),
        ),
        'そんざい' => array (
            'そ' => 
            array (
                'そんざい' => 0,
            ),
            'そん' => 
            array (
                'そんざい' => 0,
            ),
            'そんざ' => 
            array (
                'そんざい' => 0,
            ),
            'そんざい' => 
            array (
                'そんざい' => 0,
            ),
        )
    ))
);